export const CHANGE_SELECTED_COLLECTION = 'CHANGE_SELECTED_COLLECTION';
export const CLEAR_SELECTED_COLLECTION = 'CLEAR_SELECTED_COLLECTION';

export const SHOW_SCRIM = 'SHOW_SCRIM';
export const HIDE_SCRIM = 'HIDE_SCRIM';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
